### ISSUE TITLE
A branch protection setting is not enabled: requires approving reviews

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/network-access-control-integration-tests#24]
Hi there
The default branch protection setting called requires approving reviews is not enabled for this repository
See repository settings/Branches/Branch protection rules
Either add a new Branch protection rule or edit the existing branch protection rule and select the Require approvals option
This will require another persons approval on a pull request before it can be merged
See the repository standards: https://github.com/ministryofjustice/github-repository-standards
See the report: https://operations-engineering-reports.cloud-platform.service.justice.gov.uk/github_repositories
Please contact Operations Engineering on Slack #ask-operations-engineering, if you need any assistance

**Comment by Gary-H9** [comment]
As part of this ticket can we establish if this can be done in the `.github` repository?

**Comment by ASTRobinson** [comment]
I have researched branch protection settings at an organizational level and managing the protection rules in code but it appears this feature is still not available on GitHub. There are some 3rd party apps / scripts available but I suggest we manage these settings in the UI until GitHub enables this feature.

**Comment by ASTRobinson** [comment]
branch protection rule created.
